# Generated by Django 4.2.30 on 2026-04-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive stores are hidden from the public submission form.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store where the customer made their qualifying purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='campaigns.store'),
        ),
    ]
