# Generated by Django 4.2.30 on 2026-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_store_submission_image_1_submission_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='display_title',
            field=models.CharField(blank=True, help_text='Title shown in the dashboard sidebar/topbar when viewing this campaign. Falls back to the campaign name if blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the dashboard sidebar when viewing this campaign.', null=True, upload_to='campaign_logos/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='primary_color',
            field=models.CharField(blank=True, help_text="Brand accent color (hex, e.g. #e30613). Drives buttons, badges and highlights on this campaign's dashboard.", max_length=7),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sidebar_color',
            field=models.CharField(blank=True, help_text='Sidebar background color (hex, e.g. #1a2035). Optional. Falls back to a dark default if blank.', max_length=7),
        ),
    ]
