# Generated by Django 4.2.30 on 2026-05-09 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_campaign_display_title_campaign_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Users assigned here can view and manage this campaign and its submissions in the dashboard.', related_name='managed_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='invalidation_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Invalid submissions are excluded from raffles. Toggle from the dashboard or admin.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
