# Generated by Django 4.2.30 on 2026-05-20 18:56

from django.db import migrations, models
import django.db.models.deletion


def seed_default_theme(apps, schema_editor):
    Theme = apps.get_model("campaigns", "Theme")
    Theme.objects.get_or_create(
        slug="futboleros",
        defaults={
            "name": "Futboleros (Mundial 2026)",
            "description": "Original Mundial 2026 design — La Nube que te mueve",
            "is_default": True,
        },
    )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.theme'),
        ),
        migrations.RunPython(seed_default_theme, reverse_noop),
    ]
