# Generated by Django 4.2.30 on 2026-05-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_populate_default_theme_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text="Field schema for this campaign's submission form. Leave empty (or '{}') to use the default 9-field schema. See docs/superpowers/specs/2026-05-22-flexible-form-fields-design.md."),
        ),
        migrations.AddField(
            model_name='store',
            name='campaigns',
            field=models.ManyToManyField(blank=True, help_text='Campaigns this store appears in. Stores with no campaigns are hidden from all public forms.', related_name='stores', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='submission',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text="Custom field values keyed by schema 'key'. Excludes file uploads."),
        ),
        migrations.AlterField(
            model_name='submission',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_key', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='submissions/extras/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaigns.submission')),
            ],
            options={
                'ordering': ['uploaded_at'],
                'unique_together': {('submission', 'schema_key')},
            },
        ),
    ]
