# Generated by Django 4.2.30 on 2026-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_backfill_store_campaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trivia/')),
                ('image_alt', models.CharField(blank=True, default='', max_length=200)),
                ('option_a', models.CharField(max_length=120)),
                ('option_b', models.CharField(max_length=120)),
                ('option_c', models.CharField(max_length=120)),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='trivia_questions', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
